name: 'AI Code Review with Claude'
description: 'Automated code review using Claude AI with aggressive and direct feedback style'
author: '5G-HarryLu'

inputs:
  claude-api-key:
    description: 'Claude API Key (get from https://console.anthropic.com/)'
    required: true
  claude-model:
    description: 'Claude model to use (claude-sonnet-4-20250514, claude-3-7-sonnet-20250219, claude-3-5-sonnet-20241022, claude-3-5-haiku-20241022)'
    required: false
    default: 'claude-sonnet-4-20250514'
  github-token:
    description: 'GitHub Token for API access'
    required: false
    default: ${{ github.token }}
  repository:
    description: 'Repository in format owner/repo'
    required: false
    default: ${{ github.repository }}
  pr-number:
    description: 'Pull Request number to review'
    required: false
    default: ${{ github.event.pull_request.number }}

outputs:
  review-posted:
    description: 'Whether the review was successfully posted'
    value: ${{ steps.review.outputs.success }}
  comment-url:
    description: 'URL of the posted review comment'
    value: ${{ steps.review.outputs.comment_url }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        npm install --production

    - name: Build TypeScript
      shell: bash
      run: |
        cd ${{ github.action_path }}
        npm run build

    - name: Run AI Code Review
      id: review
      shell: bash
      env:
        CLAUDE_API_KEY: ${{ inputs.claude-api-key }}
        CLAUDE_MODEL: ${{ inputs.claude-model }}
        GITHUB_ACCESS_TOKEN: ${{ inputs.github-token }}
        GITHUB_REPOSITORY: ${{ inputs.repository }}
        PR_NUMBER: ${{ inputs.pr-number }}
      run: |
        cd ${{ github.action_path }}
        node ai-code-reviewer.js

branding:
  icon: 'check-circle'
  color: 'purple'
